# Generated by Django 3.0.8 on 2020-08-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chara_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
